//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJeHelperD2R {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringLib {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLib() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AJeHelperD2R.StringLib", typeof(StringLib).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Buff과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Buff {
            get {
                return ResourceManager.GetString("Buff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Donate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ing {
            get {
                return ResourceManager.GetString("Ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Just once과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Just_Once {
            get {
                return ResourceManager.GetString("Just_Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   US과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Localize {
            get {
                return ResourceManager.GetString("Localize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exchange key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mBufChangeLabel {
            get {
                return ResourceManager.GetString("mBufChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buff overlay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mBufDisplayButton {
            get {
                return ResourceManager.GetString("mBufDisplayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overlay Infomation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mBuffGroupBox {
            get {
                return ResourceManager.GetString("mBuffGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buff time(sec) :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mBuffTimeLabel {
            get {
                return ResourceManager.GetString("mBuffTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buff key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mBufKeyLabel {
            get {
                return ResourceManager.GetString("mBufKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delay between buff keys (ms)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mBufLabel {
            get {
                return ResourceManager.GetString("mBufLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mBufStartLabel {
            get {
                return ResourceManager.GetString("mBufStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouse button과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mButtonTypeLabel {
            get {
                return ResourceManager.GetString("mButtonTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start/Stop key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mControlKeyLabel {
            get {
                return ResourceManager.GetString("mControlKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat delay(ms):과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mControlRepeatLabel {
            get {
                return ResourceManager.GetString("mControlRepeatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mControlTypeLabel {
            get {
                return ResourceManager.GetString("mControlTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match the red box to the mercenary screen.
        ///Place the blue box where it should be displayed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mDescLabel {
            get {
                return ResourceManager.GetString("mDescLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound effect at the end of buff time :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mEffectLabel {
            get {
                return ResourceManager.GetString("mEffectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound effect volumn :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mEffectVolumnLabel {
            get {
                return ResourceManager.GetString("mEffectVolumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyboard and mouse input cannot be hooked.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is changed data that has not been saved. Do you still want to end it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t set the left click on the mouse!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message3 {
            get {
                return ResourceManager.GetString("Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t set the right click on the mouse!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message4 {
            get {
                return ResourceManager.GetString("Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The key is already registered!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message5 {
            get {
                return ResourceManager.GetString("Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t set the left click on the mouse!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message6 {
            get {
                return ResourceManager.GetString("Message6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t set the right click on the mouse!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message7 {
            get {
                return ResourceManager.GetString("Message7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Helper start/stop key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mGoupBox1 {
            get {
                return ResourceManager.GetString("mGoupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mGoupBox2 {
            get {
                return ResourceManager.GetString("mGoupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mGoupBox3 {
            get {
                return ResourceManager.GetString("mGoupBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mercenary과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mGoupBox4 {
            get {
                return ResourceManager.GetString("mGoupBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buff key (The check box next to the buff key is a weapon exchange)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mGoupBox5 {
            get {
                return ResourceManager.GetString("mGoupBox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image file :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mImageLabel {
            get {
                return ResourceManager.GetString("mImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mMemoLabel {
            get {
                return ResourceManager.GetString("mMemoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mercenary overlay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mMercenaryButton {
            get {
                return ResourceManager.GetString("mMercenaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mOpacityLabel {
            get {
                return ResourceManager.GetString("mOpacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouse Left과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Mouse_Left {
            get {
                return ResourceManager.GetString("Mouse_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouse Right과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Mouse_Right {
            get {
                return ResourceManager.GetString("Mouse_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Potion key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mPotionNowKeyLabel {
            get {
                return ResourceManager.GetString("mPotionNowKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mPotionReplaceKeyLabel {
            get {
                return ResourceManager.GetString("mPotionReplaceKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mProgramLabel {
            get {
                return ResourceManager.GetString("mProgramLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stand still key :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mShiftKeyLabel {
            get {
                return ResourceManager.GetString("mShiftKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stand still과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mShiftLabel {
            get {
                return ResourceManager.GetString("mShiftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skill key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mTechKeyLabel {
            get {
                return ResourceManager.GetString("mTechKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Push과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Push (Holding)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Push_Holding {
            get {
                return ResourceManager.GetString("Push_Holding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Push (Toggle)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Push_Toggle {
            get {
                return ResourceManager.GetString("Push_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat (Holding)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Repeat_Holding {
            get {
                return ResourceManager.GetString("Repeat_Holding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat (Toggle)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Repeat_Toggle {
            get {
                return ResourceManager.GetString("Repeat_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle: Press it once to execute, press it again to terminate. / Holding: Press it to execute.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolTip {
            get {
                return ResourceManager.GetString("ToolTip", resourceCulture);
            }
        }
    }
}
